### ISSUE TITLE
Any chance to get the DOM-Test-Suite into github?

### ISSUE THREAD

**Issue by karfau** [w3c/github_sync#22]
Is there still a way to get this code https://dev.w3.org/cvsweb/2001/DOM-Test-Suite/ added to the list of w3c list of github repos?

**Comment by gsnedders** [comment]
https://github.com/gsnedders/dom-test-suite has it, FWIW.

**Comment by gsnedders** [comment]
(Also, to note, this repo is about legacy infrastructure used for web-platform-tests, rather than somewhere to generically ask for things to be copied over to GitHub)
